/**
 * Premier League — joueurs marquants, des annees 1990 a aujourd'hui.
 * Un seul mot, sans accent, aucun nom compose.
 */
export const playersPremier = {
  category: 'joueur',
  tiers: {
    1: [
      'scholes', 'giggs', 'neville', 'keane', 'cole', 'yorke', 'sheringham',
      'solskjaer', 'schmeichel', 'stam', 'ronaldo', 'tevez', 'berbatov',
      'owen', 'fowler', 'mcmanaman', 'carragher', 'alonso', 'mascherano',
      'torres', 'sturridge', 'coutinho', 'firmino', 'mane', 'henderson',
      'drogba', 'cech', 'cole', 'essien', 'makelele', 'robben', 'duff',
      'ballack', 'anelka', 'mata', 'oscar', 'willian', 'costa', 'kante',
      'bergkamp', 'vieira', 'campbell', 'lehmann', 'ljungberg', 'pires',
      'adebayor', 'nasri', 'walcott', 'ramsey', 'giroud', 'sanchez', 'ozil',
      'aguero', 'silva', 'toure', 'kompany', 'hart', 'nasri', 'sane',
      'sterling', 'jesus', 'laporte', 'fernandinho', 'zabaleta',
    ],
    2: [
      'shearer', 'ferdinand', 'beardsley', 'ginola', 'asprilla', 'solano',
      'ameobi', 'given', 'nolan', 'carroll', 'cabaye', 'sissoko', 'perez',
      'lampard', 'terry', 'ivanovic', 'ramires', 'hazard', 'matic', 'luiz',
      'rooney', 'nani', 'valencia', 'evans', 'smalling', 'jones', 'vidic',
      'gerrard', 'suarez', 'skrtel', 'agger', 'lucas', 'johnson', 'sakho',
      'defoe', 'keane', 'modric', 'bale', 'vandevaart', 'adebayor', 'dembele',
      'lloris', 'alderweireld', 'vertonghen', 'eriksen', 'alli', 'kane',
      'cahill', 'jagielka', 'baines', 'fellaini', 'arteta', 'lukaku', 'barkley',
      'pienaar', 'osman', 'howard', 'coleman', 'mirallas', 'deulofeu',
      'zaha', 'benteke', 'milivojevic', 'townsend', 'ayew', 'puncheon',
      'vardy', 'mahrez', 'schmeichel', 'huth', 'morgan', 'albrighton',
      'okazaki', 'ndidi', 'maddison', 'tielemans', 'chilwell', 'iheanacho',
      'austin', 'redmond', 'tadic', 'pelle', 'vanDijk', 'bertrand', 'ward',
      'benrahma', 'antonio', 'noble', 'lanzini', 'obiang', 'reid', 'ogbonna',
      'wilshere', 'chamberlain', 'gibbs', 'monreal', 'koscielny', 'mertesacker',
      'welbeck', 'iwobi', 'elneny', 'xhaka', 'lacazette', 'aubameyang',
    ],
    3: [
      'seaman', 'winterburn', 'dixon', 'adams', 'bould', 'wright', 'merson',
      'parlour', 'petit', 'overmars', 'grimandi', 'kanu', 'silvinho',
      'butt', 'brown', 'ohara', 'fletcher', 'carrick', 'park', 'evra',
      'hargreaves', 'anderson', 'macheda', 'welbeck', 'young', 'valencia',
      'barnes', 'redknapp', 'berger', 'heskey', 'murphy', 'hyypia',
      'riise', 'kewell', 'garcia', 'crouch', 'bellamy', 'babel', 'benayoun',
      'dudek', 'kuyt', 'aurelio', 'insua', 'degen', 'voronin',
      'zola', 'poyet', 'wise', 'leboeuf', 'desailly', 'gudjohnsen', 'hasselbaink',
      'gronkjaer', 'melchiot', 'ferrer', 'lebeouf', 'petrescu', 'babayaro',
      'okocha', 'djorkaeff', 'campo', 'jaaskelainen', 'davies', 'gardner',
      'diouf', 'anelka', 'giannakopoulos', 'nolan', 'speed',
      'distin', 'lescott', 'barry', 'milner', 'johnson', 'bellamy', 'adebayor',
      'santacruz', 'petrov', 'wrightphillips', 'dunne', 'sinclair', 'ireland',
      'yaya', 'kolo', 'nasri', 'dzeko', 'balotelli', 'clichy', 'kolarov',
      'navas', 'negredo', 'nastasic', 'demichelis', 'bony', 'mangala',
      'huddlestone', 'jenas', 'lennon', 'palacios', 'kaboul', 'assouekotto',
      'sandro', 'sigurdsson', 'holtby', 'chadli', 'paulinho', 'soldado',
      'chiriches', 'capoue', 'naughton', 'walker', 'rose', 'davies',
    ],
    4: [
      'sherwood', 'anderton', 'ferdinand', 'iversen', 'rebrov', 'freund',
      'perryman', 'hoddle', 'ardiles', 'villa', 'clemence', 'waddle',
      'gascoigne', 'lineker', 'mabbutt', 'howells', 'nayim', 'samways',
      'batty', 'speed', 'strachan', 'mcallister', 'dorigo', 'chapman',
      'yeboah', 'kewell', 'bowyer', 'woodgate', 'smith', 'viduka', 'harte',
      'dacourt', 'bakke', 'radebe', 'martyn', 'mills', 'ferdinand',
      'sutton', 'flowers', 'ripley', 'wilcox', 'sherwood', 'hendry',
      'duff', 'jansen', 'dunn', 'friedel', 'todd', 'tugay', 'yorke',
      'rosenior', 'bullard', 'windass', 'ashbee', 'marney', 'garcia',
      'hughes', 'bothroyd', 'zamora', 'clark', 'boateng', 'holt', 'jelavic',
    ],
  },
};
