/**
 * Complement : joueurs des annees 1990-2010 et profils reconnaissables
 * qui manquaient aux autres modules. Un seul mot, sans accent, pas de nom compose.
 */
export const playersMore = {
  category: 'joueur',
  tiers: {
    1: [
      'vialli', 'mancini', 'signori', 'ravanelli', 'donadoni', 'albertini',
      'costacurta', 'toldo', 'peruzzi', 'panucci', 'cassano', 'gilardino',
      'montella', 'quagliarella', 'giovinco', 'palacio', 'canizares',
      'mendieta', 'guardiola', 'mijatovic', 'pauleta', 'conceicao',
      'riquelme', 'palermo', 'milito', 'heinze', 'coloccini', 'otamendi',
      'denilson', 'edmundo', 'emerson', 'juan', 'luisao', 'grafite',
      'makaay', 'cocu', 'zenden', 'reiziger', 'numan', 'afellay',
    ],
    2: [
      'iaquinta', 'borriello', 'pazzini', 'corradi', 'cordoba', 'materazzi',
      'zaccardo', 'grosso', 'barone', 'perrotta', 'oddo', 'amelia',
      'lentini', 'massaro', 'tassotti', 'evani', 'boban', 'weah',
      'papin', 'savicevic', 'simone', 'eranio', 'ziege', 'leonardo',
      'farinos', 'angulo', 'munitis', 'abelardo', 'alkorta', 'nadal',
      'amavisca', 'sanchis', 'buyo', 'chendo', 'michel', 'butragueno',
      'joaquin', 'reyes', 'baraja', 'albelda', 'aimar', 'ayala',
      'heitinga', 'mathijsen', 'bouma', 'bogarde', 'winter', 'ooijer',
      'elia', 'lens', 'promes', 'wijnaldum', 'klaassen', 'veltman',
      'blind', 'berghuis', 'malacia', 'boadu', 'stengs', 'gravenberch',
      'meireles', 'postiga', 'almeida', 'tiago', 'couto', 'sousa',
      'hitzlsperger', 'frings', 'kuranyi', 'asamoah', 'jeremies', 'linke',
      'borowski', 'metzelder', 'friedrich', 'westermann', 'marin', 'castro',
      'draxler', 'schurrle', 'kruse', 'volland', 'trochowski', 'holtby',
    ],
    3: [
      'dhorasoo', 'pedretti', 'rothen', 'frau', 'feindouno', 'luyindula',
      'saha', 'cisse', 'chimbonda', 'boumsong', 'mexes', 'escude',
      'squillaci', 'reveillere', 'jallet', 'debuchy', 'tremoulinas',
      'ciani', 'planus', 'gourcuff', 'hoarau', 'nene', 'chantome',
      'rami', 'koscielny', 'mavuba', 'obraniak', 'balmont', 'roux',
      'gignac', 'sirigu', 'douchez', 'ruffier', 'carrasso', 'gurtner',
      'costil', 'sels', 'oukidja', 'benitez', 'lafont', 'maignan',
      'briand', 'ntep', 'grenier', 'lacazette', 'fekir', 'depay',
      'aouar', 'ekambi', 'dembele', 'toko', 'guimaraes', 'paqueta',
      'thauvin', 'ocampos', 'sanson', 'lopez', 'radonjic', 'benedetto',
      'germain', 'sarr', 'amavi', 'caleta', 'gonzalez', 'guendouzi',
      'draxler', 'pastore', 'paredes', 'gueye', 'herrera', 'bernat',
      'kurzawa', 'diallo', 'icardi', 'sarabia', 'wijnaldum', 'renato',
      'alario', 'buendia', 'correa', 'gallardo', 'bernardo', 'garay',
      'elano', 'alex', 'amoroso', 'gilberto', 'cris', 'doria',
      'miranda', 'fabinho', 'arthur', 'everton', 'antony', 'martinez',
    ],
    4: [
      'kalou', 'obraniak', 'licht', 'traore', 'bakambu', 'gradel',
      'briand', 'gomis', 'sinama', 'ilan', 'moussilou', 'mouloungui',
      'nangis', 'bahoken', 'diony', 'khazri', 'sotoca', 'clauss',
      'wesley', 'bamba', 'sissoko', 'sarr', 'sylla', 'kamara',
      'plasil', 'micoud', 'rool', 'cheyrou', 'meriem', 'perrin',
      'landrin', 'nivet', 'gillet', 'gomis', 'ayite', 'bourillon',
      'grax', 'savidan', 'cvitanich', 'toure', 'coulibaly', 'diakhate',
      'cetkovic', 'ndoye', 'ideye', 'wallace', 'bocaly', 'briand',
      'suk', 'aliadiere', 'braaten', 'ideye', 'giannelli', 'imbula',
      'thomasson', 'cabot', 'grandsir', 'bahlouli', 'nordin', 'aholou',
      'silva', 'costa', 'pereira', 'moreira', 'ribeiro', 'carvalho',
      'oliveira', 'fernandes', 'gomes', 'rodrigues', 'martins', 'sousa',
    ],
  },
};
